import os

from config.config_file import HOST_ADDRESS_ORDERMANAGEMENT_DOCKER, HOST_ADDRESS_PATHPLANNING_DOCKER, \
    HOST_ADDRESS_SYSTEMSTATEMANAGEMENT_DOCKER, HOST_ADDRESS_AMRSIMULATION_DOCKER, HOST_ADDRESS_ORDERMANAGEMENT, \
    HOST_ADDRESS_PATHPLANNING, HOST_ADDRESS_SYSTEMSTATEMANAGEMENT, HOST_ADDRESS_AMRSIMULATION, PORT, \
    HOST_ADDRESS_BASEDATAMANAGEMENT_DOCKER, HOST_ADDRESS_BASEDATAMANAGEMENT, HOST_ADDRESS_TASK_ASSIGNMENT_DOCKER, \
    HOST_ADDRESS_TASK_ASSIGNMENT, HOST_ADDRESS_STORAGE_LOCATION_TRACKING_DOCKER, HOST_ADDRESS_STORAGE_LOCATION_TRACKING, \
    HOST_ADDRESS_AMRCOMMUNICATION_DOCKER, HOST_ADDRESS_AMRCOMMUNICATION
import config.config_file
from logic.general_functions import env_to_bool

port = PORT


def set_service_urls():  # in case the environment variables are not set by gitlab-ci.yml file
    ENV_DOCKER = os.environ.get('ENV_IN_DOCKER', False)
    if ENV_DOCKER == "True":
        if 'ORDERMANAGEMENT_URL' not in os.environ:
            os.environ['ORDERMANAGEMENT_URL'] = HOST_ADDRESS_ORDERMANAGEMENT_DOCKER
        if 'PATHPLANNING_URL' not in os.environ:
            os.environ['PATHPLANNING_URL'] = HOST_ADDRESS_PATHPLANNING_DOCKER
        if 'SYSTEMSTATEMANAGEMENT_URL' not in os.environ:
            os.environ['SYSTEMSTATEMANAGEMENT_URL'] = HOST_ADDRESS_SYSTEMSTATEMANAGEMENT_DOCKER
        if 'AMRSIMULATION_URL' not in os.environ:
            os.environ['AMRSIMULATION_URL'] = HOST_ADDRESS_AMRSIMULATION_DOCKER
        if 'BASEDATAMANAGEMENT_URL' not in os.environ:
            os.environ['BASEDATAMANAGEMENT_URL'] = HOST_ADDRESS_BASEDATAMANAGEMENT_DOCKER
        if 'TASKASSIGNMENT_URL' not in os.environ:
            os.environ['TASKASSIGNMENT_URL'] = HOST_ADDRESS_TASK_ASSIGNMENT_DOCKER
        if 'AMRCOMMUNICATION_URL' not in os.environ:
            os.environ['AMRCOMMUNICATION_URL'] = HOST_ADDRESS_AMRCOMMUNICATION_DOCKER
        if 'STORAGE_LOCATION_TRACKING_URL' not in os.environ:
            os.environ['STORAGE_LOCATION_TRACKING_URL'] = HOST_ADDRESS_STORAGE_LOCATION_TRACKING_DOCKER
        config.config_file.STORAGE_LOCATION_TRACKING = env_to_bool(os.environ['STORAGE_LOCATION_TRACKING'])
        config.config_file.SIMULATION_ACTIVE = env_to_bool(os.environ['AMR_SIMULATION_ACTIVE'])
    else:
        if 'ORDERMANAGEMENT_URL' not in os.environ:
            os.environ['ORDERMANAGEMENT_URL'] = HOST_ADDRESS_ORDERMANAGEMENT
        if 'PATHPLANNING_URL' not in os.environ:
            os.environ['PATHPLANNING_URL'] = HOST_ADDRESS_PATHPLANNING
        if 'SYSTEMSTATEMANAGEMENT_URL' not in os.environ:
            os.environ['SYSTEMSTATEMANAGEMENT_URL'] = HOST_ADDRESS_SYSTEMSTATEMANAGEMENT
        if 'AMRSIMULATION_URL' not in os.environ:
            os.environ['AMRSIMULATION_URL'] = HOST_ADDRESS_AMRSIMULATION
        if 'BASEDATAMANAGEMENT_URL' not in os.environ:
            os.environ['BASEDATAMANAGEMENT_URL'] = HOST_ADDRESS_BASEDATAMANAGEMENT
        if 'TASKASSIGNMENT_URL' not in os.environ:
            os.environ['TASKASSIGNMENT_URL'] = HOST_ADDRESS_TASK_ASSIGNMENT
        if 'AMRCOMMUNICATION_URL' not in os.environ:
            os.environ['AMRCOMMUNICATION_URL'] = HOST_ADDRESS_AMRCOMMUNICATION
        if 'STORAGE_LOCATION_TRACKING_URL' not in os.environ:
            os.environ['STORAGE_LOCATION_TRACKING_URL'] = HOST_ADDRESS_STORAGE_LOCATION_TRACKING


